# Generated by Django 5.2.3 on 2025-06-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyect',
            name='progress',
            field=models.IntegerField(),
        ),
    ]
