# Generated by Django 5.2.3 on 2025-06-13 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.AlterUniqueTogether(
            name='contactrequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='data',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='project',
        ),
        migrations.RemoveField(
            model_name='document',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='document',
            name='project',
        ),
        
        migrations.RemoveField(
            model_name='folder',
            name='parent_folder',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='project',
        ),
        migrations.RemoveField(
            model_name='image',
            name='page',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Chart',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ContactRequest',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
        migrations.DeleteModel(
            name='DataSet',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
